name: fenix_mobile_case
description: "A Fenix Case Study Project"


version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  #ui
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  flutter_svg: 2.2.2
  extended_image: ^10.0.1
  infinite_scroll_pagination: ^4.1.0

  #model generate
  freezed: ^3.2.3

  #state Management
  flutter_bloc: ^9.1.1

  #network
  dio: ^5.9.0

  # Routing
  go_router: ^14.0.1

  #assets
  flutter_gen: ^5.12.0


  #local storage
  sembast: ^3.8.5+2
  path_provider: ^2.1.5

  #logger
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.4.0

  #dependency injection
  get_it: ^9.0.5

  #encrypt
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  #model generate
  build_runner: ^2.10.3
  freezed_annotation: ^3.1.0
  flutter_gen_runner: ^5.12.0
  json_serializable:

flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)

  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true
  assets:
    - assets/icons/




  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

